### PR TITLE
Add .src method working with globs

### PR DESCRIPTION
**Pull request by yavorski**

### CODE REVIEW

**Comment by soyuka** [comment]
:+1: 

Would be nice to add some docs, but great work!

**Comment by ctalkington** [comment]
thanks for taking this on as I've been a bit busier to implement new features. will do a final review and release it as new version over the holiday weekend.

**Comment by yavorski** [comment]
Np. Thank you too!

**Comment by ctalkington** [comment]
0.18.0 has been published to npm. let me know how you go.

**Comment by ctalkington** [comment]
released 0.19.0 to rename this to glob for forward compatibility with possible feature

**Pull request merged**
