### PR TITLE
Remove _entries and implement progress event

### PR DESCRIPTION
**Pull request by soyuka**
title

### CODE REVIEW

**Comment by ctalkington** [comment]
so im thinking we need a little more here. since this all is based on using the fs.stats object, it doesnt account for some of the manual methods of adding entries. for example, if i add a buffer or stream.

**Comment by soyuka** [comment]
Hmm, when something is added through those manual methods, don't they go through `_moduleAppend`? Which method are you refering to?

**Comment by ctalkington** [comment]
the ones im thinking would be the ones that go through a push to _queue. directly.

**Comment by ctalkington** [comment]
that or what if we just say, `progress` is purely number of entries processed to number of entries given. then have a subpropery like `progress.fs` which has total bytes read from fs and total written

**Comment by soyuka** [comment]
We're not aware of the number of entries given, or are we?

Surely agree with `fs` mention. I'll take a look at `_queue`.

**Comment by soyuka** [comment]
#250

**Pull request closed without merging**
